name: spell_checker
version: 0.1.2+2

description: Simple spell checker for Dart using Peter Norvig's algorithm
homepage: https://github.com/almaclaine/dart_spell_checker

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.5
  effective_dart: ^1.3.1
  list_english_words:
    git:
      url: https://github.com/Letalus/dart_list_english_words.git
      ref: nullsafety